# Generated by Django 4.2.30 on 2026-05-01 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArquivoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.CharField(db_index=True, max_length=100)),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('url_onedrive', models.URLField(max_length=2048)),
                ('tamanho_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('tipo_arquivo', models.CharField(blank=True, max_length=100)),
                ('onedrive_item_id', models.CharField(blank=True, max_length=512)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Arquivo de Pedido',
                'verbose_name_plural': 'Arquivos de Pedidos',
                'ordering': ['-criado_em'],
            },
        ),
    ]
