# Generated by Django 4.2.30 on 2026-05-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_microsofttoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicrosoftToken',
        ),
    ]
