# Generated by Django 4.2.30 on 2026-05-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_delete_microsofttoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Token Microsoft',
                'verbose_name_plural': 'Tokens Microsoft',
            },
        ),
    ]
